version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notes_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6185
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./notes
    container_name: notes_app_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:6185@db:5432/notes_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: notes_frontend_container
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  postgres_data: