"""initial tables

Revision ID: ca102c8b8cfc
Revises: 
Create Date: 2026-06-15 16:02:55.047562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca102c8b8cfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notes', 'owner_id')
    # ### end Alembic commands ###
